<?php
/**
 * Homepage Template (front-page.php)
 * 
 * Automatically used when Settings → Reading → "A static page" is set as homepage.
 * Content is loaded from page-content/home.html (generated by build-theme.sh).
 */
get_header(); ?>

<main id="main-content">
    <?php echo mjsk_load_page_content('home.html'); ?>
</main>

<?php
// Boat Detail Modal (homepage only)
echo mjsk_load_page_content('home-modal.html');
?>

<?php get_footer(); ?>
